### ISSUE TITLE
Move Closable Embed Menu to discord-menu

### ISSUE THREAD

**Issue by yhgoh88** [TsubakiBotPad/discord-menu#53]
This is a nice convenience menu that reduces a lot of boilerplate. It should be part of the core lib

https://github.com/TsubakiBotPad/tsutils/blob/32f84fa0e5a32c257f43bbfb9f46da3ca70ba3e1/tsutils/menu/closable_embed_base.py

**Comment by RheingoldRiver** [comment]
that's a good idea, thanks for opening this ticket!

**Comment by yhgoh88** [comment]
https://github.com/TsubakiBotPad/discord-menu/pull/59
